export const AuditAction = {
    REQUEST_SUBMITTED: 'REQUEST_SUBMITTED',
    REQUEST_APPROVED: 'REQUEST_APPROVED',
    REQUEST_REJECTED: 'REQUEST_REJECTED',
    REQUEST_WITHDRAWN: 'REQUEST_WITHDRAWN',
    REQUEST_CANCELLED: 'REQUEST_CANCELLED',

    BALANCE_DEDUCTED: 'BALANCE_DEDUCTED',
    BALANCE_REFRESHED_REALTIME: 'BALANCE_REFRESHED_REALTIME',
    BALANCE_RECONCILED_BATCH: 'BALANCE_RECONCILED_BATCH',
    BALANCE_CONFLICT_DETECTED: 'BALANCE_CONFLICT_DETECTED',

    SYNC_STARTED: 'SYNC_STARTED',
    SYNC_COMPLETED: 'SYNC_COMPLETED',
    SYNC_FAILED: 'SYNC_FAILED',
} as const;

export type AuditActionType = (typeof AuditAction)[keyof typeof AuditAction];